# Generated by Django 6.1.1 on 2026-09-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('speaker', models.CharField(blank=True, max_length=150)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('session_type', models.CharField(choices=[('saturday', 'Saturday Session'), ('extensive', 'Extensive Session')], default='saturday', max_length=20)),
                ('room', models.CharField(default='Online — Google Meet', max_length=200)),
                ('meeting_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
