# Generated by Django 6.1.1 on 2026-09-12 10:09

import django.db.models.deletion
from django.db import migrations, models


def create_speakers(apps, schema_editor):
    Speaker = apps.get_model("core", "Speaker")
    Session = apps.get_model("core", "Session")

    speakers = {}

    for name in ["Mohammad", "Ramtin", "Nima"]:
        speaker = Speaker.objects.create(
            name=name,
            slug=name.lower(),
        )
        speakers[name] = speaker

    for session in Session.objects.all():
        if session.speaker:
            speaker = speakers.get(session.speaker)
            if speaker:
                session.speaker = speaker.id
                session.save(update_fields=["speaker"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [

        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="speakers/",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),

        migrations.AlterField(
            model_name="session",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("main", "Main Session"),
                    ("extensive", "Extensive Session"),
                ],
                default="main",
                max_length=20,
            ),
        ),

        migrations.RunPython(
            create_speakers,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name="session",
            name="speaker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="core.speaker",
            ),
        ),

        migrations.CreateModel(
            name="Subgroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150),
                ),
                (
                    "slug",
                    models.SlugField(unique=True),
                ),
                (
                    "description",
                    models.TextField(blank=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_subgroups",
                        to="core.speaker",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subgroups",
                        to="core.speaker",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),

        migrations.AddField(
            model_name="session",
            name="subgroups",
            field=models.ManyToManyField(
                blank=True,
                related_name="sessions",
                to="core.subgroup",
            ),
        ),
    ]