# Generated by Django 6.1.1 on 2026-09-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_speaker_alter_session_session_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['name'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='session',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='sessions/pdfs/'),
        ),
        migrations.AddField(
            model_name='session',
            name='recording_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
