# Generated by Django 6.1.1 on 2026-09-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_speaker_options_session_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='speaker',
        ),
        migrations.AddField(
            model_name='session',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='core.speaker'),
        ),
    ]
