# Generated by Django 6.1.1 on 2026-09-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_session_speaker_session_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('main', 'Main Session'), ('extensive', 'Extensive Session'), ('journal_club', 'Journal Club')], default='main', max_length=20),
        ),
    ]
