# Generated by Django 6.1.1 on 2026-09-16 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_session_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('resource_type', models.CharField(choices=[('paper', 'Paper'), ('book', 'Book'), ('article', 'Article'), ('website', 'Website'), ('other', 'Other')], default='paper', max_length=20)),
                ('url', models.URLField()),
                ('summary', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.session')),
            ],
            options={
                'ordering': ['resource_type', 'title'],
            },
        ),
    ]
